##################################################
#         ByteIR CI pipeline
#             
#  Format check
#
#  Open Source check
#
##################################################

name: ByteIR Check CI
trigger:
  change:
    types:
      - create
      - push
jobs:
  byteir_check:
    name: byteir format check and open source check
    image: hub.byted.org/arnold/data.aml.byteir_cpu:v10
    working-directory: byteir/byteir
    steps:
      - name: Run clang format check
        commands:
          - bash .codebase/pipelines/clang_format_check.sh
      - name: Run open source check
        commands:
          - python3 .codebase/pipelines/open_source_check.py
