##################################################
#         ByteIR CI pipeline
#             
#  Format check
#  |
#  Compiler build and check
#  |
#  +--------+---------+
#  |        |         |
#  BRT_CPU  BRT_CUDA  BRT_AsanCheck
#
##################################################

name: ByteIR CI
trigger:
  change:
    types:
    - create
    - push
jobs:
  byteir_check_format:
    name: byteir format check and open source check
    image: hub.byted.org/arnold/data.aml.byteir_cpu:v7
    working-directory: byteir/byteir
    steps:
      - name: Run clang format check
        commands:
          - bash .codebase/pipelines/clang_format_check.sh
      - name: Run open source check
        commands:
          - python3 .codebase/pipelines/open_source_check.py
  byteir_compiler_build_and_test:
    name: byteir compiler CI
    runs-on:
      spec: m1.8xlarge
    image: hub.byted.org/compile/data.aml.byteir_cuda:v7
    working-directory: byteir/byteir
    depends: [byteir_check_format]
    steps:
      - name: Build and Test ByteIR Libs
        commands:
          - bash .codebase/pipelines/compiler/build_and_lit_test.sh
  brt_check_cpu:
    name: BRT cpu test
    image: hub.byted.org/compile/data.aml.byteir_cuda:v7
    working-directory: byteir/byteir
    depends: [byteir_compiler_build_and_test]
    steps:
      - name: Build and test BRT
        commands:
          - bash .codebase/pipelines/runtime/build_and_test.sh --python
      - name: Build and test BRT external project
        commands:
          - bash .codebase/pipelines/runtime/build_external_project.sh
  brt_check_cuda:
    name: BRT cuda test
    image: hub.byted.org/compile/data.aml.byteir_cuda:v7
    working-directory: byteir/byteir
    depends: [byteir_compiler_build_and_test]
    steps:
      - name: Build and test BRT with CUDA ON
        commands:
          - bash .codebase/pipelines/runtime/build_and_test.sh --cuda --python
  brt_check_asan:
    name: BRT test with asan
    image: hub.byted.org/compile/data.aml.byteir_cuda:v7
    working-directory: byteir/byteir
    depends: [byteir_compiler_build_and_test]
    steps:
      - name: Build and test BRT with asan
        commands:
          - bash .codebase/pipelines/runtime/build_and_test.sh --cuda --asan