name: ByteIR CI
trigger:
  change:
    types:
    - create
    - push
jobs:
  byteir_compiler_tests:
    name: byteir compiler CI
    runs-on:
      spec: m1.4xlarge
    image: hub.byted.org/arnold/byteir_cuda:66dd1b5002df276db934215dfec20afb
    working-directory: byteir/byteir
    steps:
      - id: cache
        uses: actions/cache
        inputs:
            key: llvm-commit-v0
            paths:
              - ./llvm_build
            restore_keys: 
              - llvm-commit-v0
      - name: Build and Test ByteIR Libs
        commands:
          - bash .codebase/pipelines/ci.sh
