##################################################
#         ByteIR CI pipeline
#             
#  Format check
#  |
#  Compiler build and check
#  |
#  +--------+---------+
#  |        |         |
#  BRT_CPU  BRT_CUDA  BRT_AsanCheck
#
##################################################

name: ByteIR CI
trigger:
  change:
    types:
      - create
      - push
    paths:
      - "!frontends/**"
      - "!.codebase/pipelines/frontends/**"
      - "!.codebase/pipelines/copybara/**"
      - "!.codebase/pipelines/onnx_frontend_ci.yaml"
      - "!.codebase/pipelines/onnx_frontend_release.yaml"
      - "!.codebase/pipelines/tf_frontend_ci.yaml"
      - "!.codebase/pipelines/tf_frontend_release.yaml"
      - "!.codebase/pipelines/torch_frontend_ci.yaml"
      - "!.codebase/pipelines/torch_frontend_release.yaml"
      - "!.codebase/pipelines/e2e_ci.yaml"
      - "!.codebase/pipelines/daily_ci.yaml"
      - "!.codebase/pipelines/daily_copybara.yaml"
      - "!.codebase/pipelines/build_scm*.sh"
      - "!**/*.md"
jobs:
  byteir_compiler_build_and_test:
    name: byteir compiler CI
    # runs-on:
    #   spec: m1.8xlarge
    image: hub.byted.org/compile/data.aml.byteir_cuda:v10
    working-directory: byteir/byteir
    steps:
      - name: Build and Test ByteIR Libs
        commands:
          - bash .codebase/pipelines/compiler/build_and_lit_test.sh
  brt_check_cpu:
    name: BRT cpu test
    image: hub.byted.org/arnold/data.aml.byteir_cpu:v10
    working-directory: byteir/byteir
    # depends: [byteir_compiler_build_and_test]
    steps:
      - name: Build and test BRT
        commands:
          - bash .codebase/pipelines/runtime/build_and_test.sh --python
      - name: Build and test BRT external project
        commands:
          - bash .codebase/pipelines/runtime/build_external_project.sh
  brt_check_cuda:
    name: BRT cuda test
    image: hub.byted.org/compile/data.aml.byteir_cuda:v10
    working-directory: byteir/byteir
    # depends: [byteir_compiler_build_and_test]
    steps:
      - name: Build and test BRT with CUDA ON
        commands:
          - CMAKE_BUILD_PARALLEL_LEVEL=16 CUDA_VISIBLE_DEVICES=4,5,6,7 bash .codebase/pipelines/runtime/build_and_test.sh --cuda --python --no-sm80-test
  brt_check_asan:
    name: BRT test with asan
    image: hub.byted.org/compile/data.aml.byteir_cuda:v10
    working-directory: byteir/byteir
    # depends: [byteir_compiler_build_and_test]
    steps:
      - name: Build and test BRT with asan
        commands:
          - CMAKE_BUILD_PARALLEL_LEVEL=16 CUDA_VISIBLE_DEVICES=4,5,6,7 bash .codebase/pipelines/runtime/build_and_test.sh --cuda --asan --no-sm80-test
  byteir_compiler_build_and_test_python:
    name: byteir cat test CI
    runs-on:
      spec: m1.8xlarge
    image: hub.byted.org/compile/data.aml.byteir_cuda:debian11_v1
    working-directory: byteir/byteir
    steps:
      - name: Build and Test Python APIs
        commands:
          - CUDA_VISIBLE_DEVICES=4,5,6,7 bash .codebase/pipelines/compiler/build_and_test_cat.sh

