name: ByteIR Daily CI
trigger:
  manual:
  cron:
jobs:
  byteir_e2e_test:
    name: byteir E2E test CI
    runs-on:
      spec: m1.8xlarge
    image: hub.byted.org/compile/data.aml.byteir_cuda:debian11_v1
    working-directory: byteir/byteir
    steps:
      - name: Build and Test E2E
        commands:
          - CUDA_VISIBLE_DEVICES=4,5,6,7 bash .codebase/pipelines/e2e/build_and_test_e2e.sh
  # byteir_compiler_build_and_test_with_asan:
  #   name: byteir compiler CI with asan
  #   image: hub.byted.org/compile/data.aml.byteir_cuda:v10
  #   working-directory: byteir/byteir
  #   steps:
  #     - name: Build and Test ByteIR Libs
  #       commands:
  #         - bash .codebase/pipelines/compiler/build_and_lit_test.sh --asan
  send_msg:
    name: send message to byteir ci group
    image: hub.byted.org/compile/data.aml.byteir_cuda:v10
    working-directory: byteir/byteir
    depends: [byteir_e2e_test]
    steps:
      - name: Send Message
        commands:
          - python3 -m pip install requests
          - python3 .codebase/pipelines/scripts/send_feisu_msg.py
