name: ByteIR Sync with GitHub
trigger:
  manual:
  cron:
jobs:
  byteir_sync_with_github_external:
    name: sync byteir with external github repo
    runs-on:
      spec: m1.8xlarge
      env: boei18n
    image: hub.byted.org/codebase/ci_java11
    working-directory: byteir/byteir
    allow-push: true
    steps:
      - id: DelayService
        if: ${{ Event.Name == "cron" }}
        commands:
          - echo 'Delay Service Start (45 mins) ...'
          - sleep 45m
          - echo 'Delay Service End ...'
      - name: sync with github
        commands:
          - git config --global user.name "wujiawei.aml"
          - git config --global user.email "wujiawei.aml@bytedance.com"
          # NOTE: by default, copybara will checkout the destination branch, but 
          # it will fail to execute `git lfs smudge`, so we skip it here.
          - git config --global filter.lfs.smudge "git-lfs smudge --skip %f"
          - git config --global filter.lfs.process "git-lfs filter-process --skip"
          - bash .codebase/pipelines/copybara/sync_with_github.sh
  send_msg:
    name: send message to byteir ci group
    image: hub.byted.org/codebase/ci_java11
    working-directory: byteir/byteir
    depends: [byteir_sync_with_github_external]
    steps:
      - name: Send Message
        commands:
          - python3 -m pip install requests
          - python3 .codebase/pipelines/scripts/send_feisu_msg.py --ci "ByteIR Sync with GitHub" --msg "ByteIR Sync with GitHub finished. Please propose a MR from branch copybara_sync to master, update the external_mirror branch to the latest sync commit."
