name: Release onnx-frontend
trigger: 
  manual:
jobs: 
  release:
    name: Release onnx-frontend
    runs-on:
      spec: m1.8xlarge
    image: hub.byted.org/arnold/data.aml.byteir_cpu:v4
    working-directory: byteir/onnx-frontend
    envs:
      TOS_ACCESS_KEY: ${{TOS_ACCESS_KEY}}
      TOS_BUCKET: ${{TOS_BUCKET}}
    steps:
      - name: Build and release onnx-frontend
        commands:
          - bash .codebase/pipelines/frontends/onnx-frontend/build_and_test.sh
          - bash .codebase/pipelines/frontends/onnx-frontend/upload_to_tos.sh
