name: TorchFrontend CI
trigger:
  change:
    paths:
      - "frontends/torch-frontend/**"
      - ".codebase/pipelines/torch_frontend_ci.yaml"
      - ".codebase/pipelines/frontends/torch-frontend/**"
jobs:
  torch_frontend_build:
    name: torch-frontend CI
    runs-on:
      spec: m1.8xlarge
    image: hub.byted.org/compile/data.aml.byteir_cuda:5e63a950ea08a0ebf5eb958b627c0f31
    working-directory: byteir/torch-frontend
    steps:
      - name: Build TorchFrontend
        commands:
          - bash .codebase/pipelines/frontends/torch-frontend/build_with_prebuilt.sh
      - name: Test
        commands:
          - bash .codebase/pipelines/frontends/torch-frontend/test.sh