name: TorchFrontend CI
trigger:
  manual:
jobs:
  torch_frontend_build:
    name: torch-frontend Release CI
    image: hub.byted.org/arnold/data.aml.byteir_cpu:v11
    working-directory: byteir/torch-frontend
    envs:
      TOS_ACCESS_KEY: ${{TOS_ACCESS_KEY}}
      TOS_BUCKET: ${{TOS_BUCKET}}
    steps:
      - name: Build TorchFrontend
        commands:
          - bash .codebase/pipelines/frontends/torch-frontend/build_with_prebuilt.sh
      - name: Upload to TOS
        commands:
          - bash .codebase/pipelines/frontends/torch-frontend/upload_to_tos.sh