name: TorchFrontend CI
trigger:
  change:
    types:
      - create
      - push
    paths:
      - "frontends/torch-frontend/**"
      - ".codebase/pipelines/torch_frontend_ci.yaml"
      - ".codebase/pipelines/frontends/torch-frontend/**"
      - "compiler/dialects/include/byteir/Dialect/Ccl/**"
      - "compiler/dialects/lib/Dialect/Ccl/**"
      - "!**/*.md"
      - "!frontends/torch-frontend/doc/**"
      - "!frontends/torch-frontend/examples/**"
      - "!frontends/torch-frontend/torch-frontend/python/version.txt"
jobs:
  torch_frontend_build:
    name: torch-frontend CI
    image: hub.byted.org/compile/data.aml.byteir_cuda:v11
    working-directory: byteir/torch-frontend
    steps:
      - name: Build TorchFrontend
        commands:
          - bash .codebase/pipelines/frontends/torch-frontend/build_with_prebuilt.sh
      - name: Test
        commands:
          - bash .codebase/pipelines/frontends/torch-frontend/test.sh