workspace(name = "org_byted_code_byteir/byteir".replace("/", "_"))

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazelize",
    type = "tar.gz",
    urls = [
        "https://{}/repository/scm/api/v1/download_latest/?name=bazel/bazelize/rules".format(
            x,
        )
        for x in [
            "luban-source.byted.org",
            "luban-source.tiktokd.org",
        ]
    ],
)

load("@bazelize//rules/common:common_deps.bzl", "common_deps")

common_deps()

load("@bazelize//rules/common:workspace_init.bzl", "workspace_init")

workspace_init()
